/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.Color;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author Amar
 */
public class AdminGUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminGUI
     */
    public AdminGUI() {
        setUndecorated(true);
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPnl = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        editprofileBtn = new keeptoo.KButton();
        logoutBtn = new keeptoo.KButton();
        exitBtn = new keeptoo.KButton();
        jLabel7 = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        logoutBtn1 = new keeptoo.KButton();
        jPanel3 = new javax.swing.JPanel();
        userMngPnl = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        editPhyPnl = new keeptoo.KGradientPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        logoutBtn2 = new keeptoo.KButton();
        logoutBtn3 = new keeptoo.KButton();
        logoutBtn4 = new keeptoo.KButton();
        jTextField1 = new javax.swing.JTextField();
        editPatientPnl = new keeptoo.KGradientPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        logoutBtn5 = new keeptoo.KButton();
        jTextField2 = new javax.swing.JTextField();
        logoutBtn6 = new keeptoo.KButton();
        logoutBtn7 = new keeptoo.KButton();
        editAppointmentPnl = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        logoutBtn8 = new keeptoo.KButton();
        logoutBtn9 = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        mainPnl.setkStartColor(new java.awt.Color(153, 204, 255));
        mainPnl.setLayout(new java.awt.BorderLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/adminpic.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 891, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPnl.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        editprofileBtn.setBorder(null);
        editprofileBtn.setText("User management");
        editprofileBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        editprofileBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        editprofileBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        editprofileBtn.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        editprofileBtn.setkPressedColor(new java.awt.Color(0, 0, 0));
        editprofileBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        editprofileBtn.setkStartColor(new java.awt.Color(102, 102, 102));
        editprofileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editprofileBtnActionPerformed(evt);
            }
        });

        logoutBtn.setBorder(null);
        logoutBtn.setText("Logout");
        logoutBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        logoutBtn.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        logoutBtn.setkPressedColor(new java.awt.Color(0, 0, 0));
        logoutBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        logoutBtn.setkStartColor(new java.awt.Color(102, 102, 102));

        exitBtn.setBorder(null);
        exitBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        exitBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        exitBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        exitBtn.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        exitBtn.setkPressedColor(new java.awt.Color(0, 0, 0));
        exitBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        exitBtn.setkStartColor(new java.awt.Color(102, 102, 102));
        exitBtn.setLabel("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", 2, 20)); // NOI18N
        jLabel7.setText("Welcome");

        welcomeLbl.setFont(new java.awt.Font("Baskerville Old Face", 2, 20)); // NOI18N
        welcomeLbl.setText("Name");

        logoutBtn1.setBorder(null);
        logoutBtn1.setText("Appointment menagment");
        logoutBtn1.setkEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn1.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        logoutBtn1.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        logoutBtn1.setkPressedColor(new java.awt.Color(0, 0, 0));
        logoutBtn1.setkSelectedColor(new java.awt.Color(255, 255, 255));
        logoutBtn1.setkStartColor(new java.awt.Color(102, 102, 102));
        logoutBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
            .addComponent(exitBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(welcomeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(logoutBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(editprofileBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(welcomeLbl)
                .addGap(64, 64, 64)
                .addComponent(editprofileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        mainPnl.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setLayout(new java.awt.CardLayout());

        userMngPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        userMngPnl.setkStartColor(new java.awt.Color(153, 153, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/doctor-3552.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/cough-3253 (1).png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel4.setText("Choose category");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Physician");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Patient");

        javax.swing.GroupLayout userMngPnlLayout = new javax.swing.GroupLayout(userMngPnl);
        userMngPnl.setLayout(userMngPnlLayout);
        userMngPnlLayout.setHorizontalGroup(
            userMngPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userMngPnlLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(130, 130, 130))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userMngPnlLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(userMngPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(userMngPnlLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(51, 51, 51)
                        .addComponent(jLabel3)))
                .addGap(31, 31, 31))
        );
        userMngPnlLayout.setVerticalGroup(
            userMngPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userMngPnlLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addGap(33, 33, 33)
                .addGroup(userMngPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(userMngPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(64, 64, 64))
        );

        jPanel3.add(userMngPnl, "card4");

        editPhyPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        editPhyPnl.setkStartColor(new java.awt.Color(153, 153, 153));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel10.setText("Physician list");

        jTable2.setBackground(new java.awt.Color(204, 204, 204));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Amar", null, null, "wda", null},
                {"2", "Sascha", null, null, "dwda", null},
                {"3", "Achim", null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "First name", "Last name", "Specification", "E-Mail ", "Phone"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        logoutBtn2.setBorder(null);
        logoutBtn2.setText("Search");
        logoutBtn2.setkEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn2.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        logoutBtn2.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        logoutBtn2.setkPressedColor(new java.awt.Color(0, 0, 0));
        logoutBtn2.setkSelectedColor(new java.awt.Color(255, 255, 255));
        logoutBtn2.setkStartColor(new java.awt.Color(102, 102, 102));

        logoutBtn3.setBorder(null);
        logoutBtn3.setText("Delete Physician");
        logoutBtn3.setkEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn3.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn3.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        logoutBtn3.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        logoutBtn3.setkPressedColor(new java.awt.Color(0, 0, 0));
        logoutBtn3.setkSelectedColor(new java.awt.Color(255, 255, 255));
        logoutBtn3.setkStartColor(new java.awt.Color(102, 102, 102));

        logoutBtn4.setBorder(null);
        logoutBtn4.setText("Create Physician");
        logoutBtn4.setkEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn4.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn4.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        logoutBtn4.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        logoutBtn4.setkPressedColor(new java.awt.Color(0, 0, 0));
        logoutBtn4.setkSelectedColor(new java.awt.Color(255, 255, 255));
        logoutBtn4.setkStartColor(new java.awt.Color(102, 102, 102));
        logoutBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtn4ActionPerformed(evt);
            }
        });

        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("Type here to search...");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout editPhyPnlLayout = new javax.swing.GroupLayout(editPhyPnl);
        editPhyPnl.setLayout(editPhyPnlLayout);
        editPhyPnlLayout.setHorizontalGroup(
            editPhyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
            .addGroup(editPhyPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editPhyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPhyPnlLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPhyPnlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(editPhyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPhyPnlLayout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(logoutBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPhyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(logoutBtn4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                .addComponent(logoutBtn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        editPhyPnlLayout.setVerticalGroup(
            editPhyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPhyPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(22, 22, 22)
                .addGroup(editPhyPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(logoutBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(logoutBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jPanel3.add(editPhyPnl, "card2");

        editPatientPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        editPatientPnl.setkStartColor(new java.awt.Color(153, 153, 153));

        jTable3.setBackground(new java.awt.Color(204, 204, 204));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Dirk", null, null, "dsd", null},
                {"2", "Marcel", null, null, null, null},
                {"3", "Dino", null, null, "s", null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "First name", "Last name", "Address", "E-Mail ", "Phone"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel11.setText("Patient list");

        logoutBtn5.setBorder(null);
        logoutBtn5.setText("Search");
        logoutBtn5.setkEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn5.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn5.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        logoutBtn5.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        logoutBtn5.setkPressedColor(new java.awt.Color(0, 0, 0));
        logoutBtn5.setkSelectedColor(new java.awt.Color(255, 255, 255));
        logoutBtn5.setkStartColor(new java.awt.Color(102, 102, 102));

        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setText("Type here to search...");
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });

        logoutBtn6.setBorder(null);
        logoutBtn6.setText("Delete patient");
        logoutBtn6.setkEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn6.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn6.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        logoutBtn6.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        logoutBtn6.setkPressedColor(new java.awt.Color(0, 0, 0));
        logoutBtn6.setkSelectedColor(new java.awt.Color(255, 255, 255));
        logoutBtn6.setkStartColor(new java.awt.Color(102, 102, 102));

        logoutBtn7.setBorder(null);
        logoutBtn7.setText("Create patient");
        logoutBtn7.setkEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn7.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn7.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        logoutBtn7.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        logoutBtn7.setkPressedColor(new java.awt.Color(0, 0, 0));
        logoutBtn7.setkSelectedColor(new java.awt.Color(255, 255, 255));
        logoutBtn7.setkStartColor(new java.awt.Color(102, 102, 102));
        logoutBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtn7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editPatientPnlLayout = new javax.swing.GroupLayout(editPatientPnl);
        editPatientPnl.setLayout(editPatientPnlLayout);
        editPatientPnlLayout.setHorizontalGroup(
            editPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPatientPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                    .addGroup(editPatientPnlLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPatientPnlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(editPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPatientPnlLayout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(logoutBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(logoutBtn7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(logoutBtn6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        editPatientPnlLayout.setVerticalGroup(
            editPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPatientPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(8, 8, 8)
                .addGroup(editPatientPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(logoutBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jPanel3.add(editPatientPnl, "card2");

        editAppointmentPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        editAppointmentPnl.setkStartColor(new java.awt.Color(153, 153, 153));

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Patient", "Physician", "Appointment date and time"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        logoutBtn8.setBorder(null);
        logoutBtn8.setText("Create appointment");
        logoutBtn8.setkEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn8.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn8.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        logoutBtn8.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        logoutBtn8.setkPressedColor(new java.awt.Color(0, 0, 0));
        logoutBtn8.setkSelectedColor(new java.awt.Color(255, 255, 255));
        logoutBtn8.setkStartColor(new java.awt.Color(102, 102, 102));

        logoutBtn9.setBorder(null);
        logoutBtn9.setText("Delete patient");
        logoutBtn9.setkEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn9.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn9.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        logoutBtn9.setkHoverStartColor(new java.awt.Color(0, 0, 0));
        logoutBtn9.setkPressedColor(new java.awt.Color(0, 0, 0));
        logoutBtn9.setkSelectedColor(new java.awt.Color(255, 255, 255));
        logoutBtn9.setkStartColor(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout editAppointmentPnlLayout = new javax.swing.GroupLayout(editAppointmentPnl);
        editAppointmentPnl.setLayout(editAppointmentPnlLayout);
        editAppointmentPnlLayout.setHorizontalGroup(
            editAppointmentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editAppointmentPnlLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(editAppointmentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutBtn8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutBtn9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        editAppointmentPnlLayout.setVerticalGroup(
            editAppointmentPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editAppointmentPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(logoutBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(logoutBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jPanel3.add(editAppointmentPnl, "card2");

        mainPnl.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(mainPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editprofileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editprofileBtnActionPerformed
     
        editPatientPnl.setVisible(false);
        editPhyPnl.setVisible(false);
        userMngPnl.setVisible(true);
    }//GEN-LAST:event_editprofileBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed

        dispose();

    }//GEN-LAST:event_exitBtnActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        editPhyPnl.setVisible(false);
        userMngPnl.setVisible(false);
        editPhyPnl.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        editPhyPnl.setVisible(false);
       
        userMngPnl.setVisible(false);
        editPatientPnl.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void logoutBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtn1ActionPerformed
        editPhyPnl.setVisible(false);
        userMngPnl.setVisible(false);
        editPatientPnl.setVisible(false);
        editAppointmentPnl.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_logoutBtn1ActionPerformed

    private void logoutBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutBtn4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
    jTextField1.setText("");
    jTextField1.setForeground(Color.black);
    }//GEN-LAST:event_jTextField1MouseClicked

    private void logoutBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtn7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutBtn7ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        jTextField2.setText("");
        jTextField2.setForeground(Color.black);

    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
    DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
    TableRowSorter<DefaultTableModel>tr= new TableRowSorter<DefaultTableModel>(model);
    jTable2.setRowSorter(tr);
    tr.setRowFilter(RowFilter.regexFilter(jTextField1.getText().trim()));
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
    DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
    TableRowSorter<DefaultTableModel>tr= new TableRowSorter<DefaultTableModel>(model);
    jTable2.setRowSorter(tr);
    tr.setRowFilter(RowFilter.regexFilter(jTextField1.getText().trim()));
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
    DefaultTableModel model=(DefaultTableModel)jTable3.getModel();
    TableRowSorter<DefaultTableModel>tr= new TableRowSorter<DefaultTableModel>(model);
    jTable3.setRowSorter(tr);
    tr.setRowFilter(RowFilter.regexFilter(jTextField2.getText().trim()));        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
    DefaultTableModel model=(DefaultTableModel)jTable3.getModel();
    TableRowSorter<DefaultTableModel>tr= new TableRowSorter<DefaultTableModel>(model);
    jTable3.setRowSorter(tr);
    tr.setRowFilter(RowFilter.regexFilter(jTextField2.getText().trim()));        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2KeyReleased

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KGradientPanel editAppointmentPnl;
    private keeptoo.KGradientPanel editPatientPnl;
    private keeptoo.KGradientPanel editPhyPnl;
    private keeptoo.KButton editprofileBtn;
    private keeptoo.KButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private keeptoo.KButton logoutBtn;
    private keeptoo.KButton logoutBtn1;
    private keeptoo.KButton logoutBtn2;
    private keeptoo.KButton logoutBtn3;
    private keeptoo.KButton logoutBtn4;
    private keeptoo.KButton logoutBtn5;
    private keeptoo.KButton logoutBtn6;
    private keeptoo.KButton logoutBtn7;
    private keeptoo.KButton logoutBtn8;
    private keeptoo.KButton logoutBtn9;
    private keeptoo.KGradientPanel mainPnl;
    private keeptoo.KGradientPanel userMngPnl;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
