/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class PatientGUI extends javax.swing.JFrame {

    /**
     * Creates new form v1PatientGUI
     */
    public PatientGUI() {
        
        setUndecorated(true);
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPnl = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        framePicLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        menuBarHomeBtn = new keeptoo.KButton();
        menuBarEditprofileBtn = new keeptoo.KButton();
        lmenuBarLogoutBtn = new keeptoo.KButton();
        menuBarExitBtn = new keeptoo.KButton();
        welcomeLbl = new javax.swing.JLabel();
        welcomNameLbl = new javax.swing.JLabel();
        menuBarNewAppBtn = new keeptoo.KButton();
        jPanel3 = new javax.swing.JPanel();
        p1 = new keeptoo.KGradientPanel();
        sendAlternativekButton6 = new keeptoo.KButton();
        patientAppointmentTable = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        yourAppointmenstLbl = new javax.swing.JLabel();
        porfilePnl = new keeptoo.KGradientPanel();
        nameLbl = new javax.swing.JLabel();
        NameTxtfld = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        familyNameLbl = new javax.swing.JLabel();
        userNameLbl = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        specificationLbl = new javax.swing.JLabel();
        addressLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        phoneLbl = new javax.swing.JLabel();
        familynameTxtfld = new javax.swing.JLabel();
        usernameTxtfld = new javax.swing.JTextField();
        titleTxtfld = new javax.swing.JTextField();
        specificationTxtfld = new javax.swing.JTextField();
        AddressTxtfld = new javax.swing.JTextField();
        emailTxtfld = new javax.swing.JTextField();
        phoneTxtfld = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        logoutBtn1 = new keeptoo.KButton();
        newAppPnl = new keeptoo.KGradientPanel();
        appointmentjDateChooserPatint = new com.toedter.calendar.JDateChooser();
        appointmentDateLbl = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        reminderLbl = new javax.swing.JLabel();
        searchdistanceLbl = new javax.swing.JLabel();
        searchDistanceTexfld = new javax.swing.JTextField();
        sendRequeskButton = new keeptoo.KButton();
        SendAlternative = new keeptoo.KGradientPanel();
        sendFirstAlternativejDateChooser = new com.toedter.calendar.JDateChooser();
        chooseFirstAterantivedateLbl = new javax.swing.JLabel();
        ChooseSecondAterantivedateLbl = new javax.swing.JLabel();
        sendSecondAlternativejDateChooser = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        addnoteTexFld = new javax.swing.JTextArea();
        addNotelbl = new javax.swing.JLabel();
        sendAppointmntRequestBtn = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        mainPnl.setkStartColor(new java.awt.Color(153, 204, 255));
        mainPnl.setLayout(new java.awt.BorderLayout());

        framePicLbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\Amar\\Desktop\\patient.png")); // NOI18N
        framePicLbl.setText("jLabel8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(framePicLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 891, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(framePicLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPnl.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        menuBarHomeBtn.setBorder(null);
        menuBarHomeBtn.setText("Home");
        menuBarHomeBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        menuBarHomeBtn.setkForeGround(new java.awt.Color(0, 0, 0));
        menuBarHomeBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        menuBarHomeBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        menuBarHomeBtn.setkHoverStartColor(new java.awt.Color(51, 255, 51));
        menuBarHomeBtn.setkPressedColor(new java.awt.Color(51, 255, 51));
        menuBarHomeBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        menuBarHomeBtn.setkStartColor(new java.awt.Color(102, 255, 102));
        menuBarHomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBarHomeBtnActionPerformed(evt);
            }
        });

        menuBarEditprofileBtn.setBorder(null);
        menuBarEditprofileBtn.setText("Edit profile");
        menuBarEditprofileBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        menuBarEditprofileBtn.setkForeGround(new java.awt.Color(0, 0, 0));
        menuBarEditprofileBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        menuBarEditprofileBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        menuBarEditprofileBtn.setkHoverStartColor(new java.awt.Color(51, 255, 51));
        menuBarEditprofileBtn.setkPressedColor(new java.awt.Color(51, 255, 51));
        menuBarEditprofileBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        menuBarEditprofileBtn.setkStartColor(new java.awt.Color(102, 255, 102));
        menuBarEditprofileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBarEditprofileBtnActionPerformed(evt);
            }
        });

        lmenuBarLogoutBtn.setBorder(null);
        lmenuBarLogoutBtn.setText("Logout");
        lmenuBarLogoutBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        lmenuBarLogoutBtn.setkForeGround(new java.awt.Color(0, 0, 0));
        lmenuBarLogoutBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        lmenuBarLogoutBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        lmenuBarLogoutBtn.setkHoverStartColor(new java.awt.Color(51, 255, 51));
        lmenuBarLogoutBtn.setkPressedColor(new java.awt.Color(51, 255, 51));
        lmenuBarLogoutBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        lmenuBarLogoutBtn.setkStartColor(new java.awt.Color(102, 255, 102));

        menuBarExitBtn.setBorder(null);
        menuBarExitBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        menuBarExitBtn.setkForeGround(new java.awt.Color(51, 51, 51));
        menuBarExitBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        menuBarExitBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        menuBarExitBtn.setkHoverStartColor(new java.awt.Color(51, 255, 51));
        menuBarExitBtn.setkPressedColor(new java.awt.Color(51, 255, 51));
        menuBarExitBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        menuBarExitBtn.setkStartColor(new java.awt.Color(102, 255, 102));
        menuBarExitBtn.setLabel("Exit");
        menuBarExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBarExitBtnActionPerformed(evt);
            }
        });

        welcomeLbl.setFont(new java.awt.Font("Baskerville Old Face", 2, 20)); // NOI18N
        welcomeLbl.setText("Welcome");

        welcomNameLbl.setFont(new java.awt.Font("Baskerville Old Face", 2, 20)); // NOI18N
        welcomNameLbl.setText("Name");

        menuBarNewAppBtn.setBorder(null);
        menuBarNewAppBtn.setText("New appointment");
        menuBarNewAppBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        menuBarNewAppBtn.setkForeGround(new java.awt.Color(0, 0, 0));
        menuBarNewAppBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        menuBarNewAppBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        menuBarNewAppBtn.setkHoverStartColor(new java.awt.Color(51, 255, 51));
        menuBarNewAppBtn.setkPressedColor(new java.awt.Color(51, 255, 51));
        menuBarNewAppBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        menuBarNewAppBtn.setkStartColor(new java.awt.Color(102, 255, 102));
        menuBarNewAppBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBarNewAppBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBarHomeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
            .addComponent(menuBarEditprofileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lmenuBarLogoutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuBarExitBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(welcomNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(menuBarNewAppBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(welcomeLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(welcomNameLbl)
                .addGap(32, 32, 32)
                .addComponent(menuBarHomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuBarEditprofileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuBarNewAppBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lmenuBarLogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(menuBarExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        mainPnl.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setLayout(new java.awt.CardLayout());

        p1.setkEndColor(new java.awt.Color(255, 255, 255));
        p1.setkStartColor(new java.awt.Color(204, 255, 204));

        sendAlternativekButton6.setBorder(null);
        sendAlternativekButton6.setText("Send alternative");
        sendAlternativekButton6.setkEndColor(new java.awt.Color(102, 255, 102));
        sendAlternativekButton6.setkForeGround(new java.awt.Color(0, 0, 0));
        sendAlternativekButton6.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        sendAlternativekButton6.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        sendAlternativekButton6.setkHoverStartColor(new java.awt.Color(102, 255, 102));
        sendAlternativekButton6.setkPressedColor(new java.awt.Color(204, 255, 204));
        sendAlternativekButton6.setkSelectedColor(new java.awt.Color(255, 255, 255));
        sendAlternativekButton6.setkStartColor(new java.awt.Color(255, 255, 255));
        sendAlternativekButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendAlternativekButton6ActionPerformed(evt);
            }
        });

        jTable2.setBackground(new java.awt.Color(204, 255, 204));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Physican 1", "Spec1", "date", "xxx@..."},
                {"Physican 2", "Spec 2", "date", "xxx@..."},
                {"Physican 3", "Spec3", "date", "xxx@..."},
                {"Physican4", "Spec4", "date", null},
                {null, null, null, null},
                {null, null, "", null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Physician", "Specalization", "Appointment date", "Physician E-Mail"
            }
        ));
        patientAppointmentTable.setViewportView(jTable2);

        yourAppointmenstLbl.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        yourAppointmenstLbl.setText("Your Appointments");

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p1Layout.createSequentialGroup()
                        .addComponent(yourAppointmenstLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(patientAppointmentTable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                            .addGroup(p1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(sendAlternativekButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(yourAppointmenstLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(patientAppointmentTable, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(sendAlternativekButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        jPanel3.add(p1, "card2");

        porfilePnl.setkEndColor(new java.awt.Color(255, 255, 255));
        porfilePnl.setkStartColor(new java.awt.Color(204, 255, 204));

        nameLbl.setText("Name");

        NameTxtfld.setText("jLabel10");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/edit.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11mouseExited(evt);
            }
        });

        familyNameLbl.setText("Family name");

        userNameLbl.setText("User name");

        titleLbl.setText("Title");

        specificationLbl.setText("Specification");

        addressLbl.setText("Address");

        emailLbl.setText("E-Mail");

        phoneLbl.setText("Phone");

        familynameTxtfld.setText("jLabel18");

        usernameTxtfld.setText("jTextField1");

        titleTxtfld.setText("jTextField2");

        specificationTxtfld.setText("jTextField3");

        AddressTxtfld.setText("jTextField4");

        emailTxtfld.setText("jTextField5");

        phoneTxtfld.setText("jTextField6");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/edit.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel19mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel19mouseExited(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/edit.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel21mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel21mouseExited(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/edit.png"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel22mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel22mouseExited(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/edit.png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel23mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel23mouseExited(evt);
            }
        });

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/edit.png"))); // NOI18N
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel24mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel24mouseExited(evt);
            }
        });

        logoutBtn1.setBorder(null);
        logoutBtn1.setText("Save changes");
        logoutBtn1.setkEndColor(new java.awt.Color(51, 255, 51));
        logoutBtn1.setkForeGround(new java.awt.Color(0, 0, 0));
        logoutBtn1.setkHoverEndColor(new java.awt.Color(102, 255, 102));
        logoutBtn1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        logoutBtn1.setkHoverStartColor(new java.awt.Color(102, 255, 102));
        logoutBtn1.setkPressedColor(new java.awt.Color(102, 255, 102));
        logoutBtn1.setkSelectedColor(new java.awt.Color(255, 255, 255));
        logoutBtn1.setkStartColor(new java.awt.Color(255, 255, 255));
        logoutBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout porfilePnlLayout = new javax.swing.GroupLayout(porfilePnl);
        porfilePnl.setLayout(porfilePnlLayout);
        porfilePnlLayout.setHorizontalGroup(
            porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(porfilePnlLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(porfilePnlLayout.createSequentialGroup()
                        .addComponent(addressLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21))
                    .addGroup(porfilePnlLayout.createSequentialGroup()
                        .addComponent(emailLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel23))
                    .addGroup(porfilePnlLayout.createSequentialGroup()
                        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, porfilePnlLayout.createSequentialGroup()
                                .addComponent(titleLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(titleTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, porfilePnlLayout.createSequentialGroup()
                                .addComponent(phoneLbl)
                                .addGap(99, 99, 99)
                                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(specificationTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phoneTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddressTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(specificationLbl)
                            .addGroup(porfilePnlLayout.createSequentialGroup()
                                .addComponent(userNameLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(usernameTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(porfilePnlLayout.createSequentialGroup()
                        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(familyNameLbl)
                            .addComponent(nameLbl))
                        .addGap(70, 70, 70)
                        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(familynameTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 99, Short.MAX_VALUE)))
                .addContainerGap(216, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, porfilePnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        porfilePnlLayout.setVerticalGroup(
            porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(porfilePnlLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameLbl)
                    .addComponent(NameTxtfld))
                .addGap(18, 18, 18)
                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(familyNameLbl)
                    .addComponent(familynameTxtfld))
                .addGap(18, 18, 18)
                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(userNameLbl)
                        .addComponent(usernameTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(titleLbl)
                        .addComponent(titleTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(specificationLbl)
                        .addComponent(specificationTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addressLbl)
                        .addComponent(AddressTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailLbl)
                    .addComponent(emailTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneLbl)
                    .addComponent(phoneTxtfld, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(logoutBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jPanel3.add(porfilePnl, "card4");

        newAppPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        newAppPnl.setkStartColor(new java.awt.Color(153, 255, 153));

        appointmentjDateChooserPatint.setBackground(new java.awt.Color(204, 255, 204));

        appointmentDateLbl.setText("Appointment date :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "one week", "3 days", "1 hour", "10 min" }));

        reminderLbl.setText("Set reminder:");

        searchdistanceLbl.setText("Search distance:");

        sendRequeskButton.setBorder(null);
        sendRequeskButton.setText("Send request");
        sendRequeskButton.setkEndColor(new java.awt.Color(255, 255, 255));
        sendRequeskButton.setkForeGround(new java.awt.Color(0, 0, 0));
        sendRequeskButton.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        sendRequeskButton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        sendRequeskButton.setkHoverStartColor(new java.awt.Color(51, 255, 51));
        sendRequeskButton.setkPressedColor(new java.awt.Color(51, 255, 51));
        sendRequeskButton.setkSelectedColor(new java.awt.Color(255, 255, 255));
        sendRequeskButton.setkStartColor(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout newAppPnlLayout = new javax.swing.GroupLayout(newAppPnl);
        newAppPnl.setLayout(newAppPnlLayout);
        newAppPnlLayout.setHorizontalGroup(
            newAppPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newAppPnlLayout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addGroup(newAppPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reminderLbl)
                    .addComponent(appointmentDateLbl)
                    .addComponent(searchdistanceLbl))
                .addGap(202, 202, 202)
                .addGroup(newAppPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(appointmentjDateChooserPatint, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchDistanceTexfld, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newAppPnlLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sendRequeskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        newAppPnlLayout.setVerticalGroup(
            newAppPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newAppPnlLayout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addGroup(newAppPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchdistanceLbl)
                    .addComponent(searchDistanceTexfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(newAppPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(appointmentjDateChooserPatint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appointmentDateLbl))
                .addGap(38, 38, 38)
                .addGroup(newAppPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reminderLbl))
                .addGap(66, 66, 66)
                .addComponent(sendRequeskButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        jPanel3.add(newAppPnl, "card2");

        SendAlternative.setkEndColor(new java.awt.Color(255, 255, 255));
        SendAlternative.setkStartColor(new java.awt.Color(153, 255, 153));

        sendFirstAlternativejDateChooser.setBackground(new java.awt.Color(204, 255, 204));

        chooseFirstAterantivedateLbl.setText("Choose first alternative date:");

        ChooseSecondAterantivedateLbl.setText("Choose second alternative date:");

        sendSecondAlternativejDateChooser.setBackground(new java.awt.Color(204, 255, 204));

        addnoteTexFld.setColumns(20);
        addnoteTexFld.setRows(5);
        jScrollPane1.setViewportView(addnoteTexFld);

        addNotelbl.setText("Add note:");

        sendAppointmntRequestBtn.setBorder(null);
        sendAppointmntRequestBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/send-4008.png"))); // NOI18N
        sendAppointmntRequestBtn.setText(" Send request");
        sendAppointmntRequestBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        sendAppointmntRequestBtn.setkForeGround(new java.awt.Color(0, 0, 0));
        sendAppointmntRequestBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        sendAppointmntRequestBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        sendAppointmntRequestBtn.setkHoverStartColor(new java.awt.Color(51, 255, 51));
        sendAppointmntRequestBtn.setkPressedColor(new java.awt.Color(51, 255, 51));
        sendAppointmntRequestBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        sendAppointmntRequestBtn.setkStartColor(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout SendAlternativeLayout = new javax.swing.GroupLayout(SendAlternative);
        SendAlternative.setLayout(SendAlternativeLayout);
        SendAlternativeLayout.setHorizontalGroup(
            SendAlternativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SendAlternativeLayout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addGroup(SendAlternativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SendAlternativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SendAlternativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SendAlternativeLayout.createSequentialGroup()
                                .addComponent(chooseFirstAterantivedateLbl)
                                .addGap(318, 318, 318))
                            .addGroup(SendAlternativeLayout.createSequentialGroup()
                                .addComponent(ChooseSecondAterantivedateLbl)
                                .addGap(303, 303, 303)))
                        .addGroup(SendAlternativeLayout.createSequentialGroup()
                            .addComponent(addNotelbl)
                            .addGap(184, 184, 184)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SendAlternativeLayout.createSequentialGroup()
                        .addGroup(SendAlternativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(SendAlternativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(sendSecondAlternativejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(SendAlternativeLayout.createSequentialGroup()
                                .addGap(0, 212, Short.MAX_VALUE)
                                .addGroup(SendAlternativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sendFirstAlternativejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sendAppointmntRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(90, 90, 90))))
        );
        SendAlternativeLayout.setVerticalGroup(
            SendAlternativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SendAlternativeLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(SendAlternativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sendFirstAlternativejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseFirstAterantivedateLbl))
                .addGap(33, 33, 33)
                .addGroup(SendAlternativeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChooseSecondAterantivedateLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sendSecondAlternativejDateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(addNotelbl)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(sendAppointmntRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        jPanel3.add(SendAlternative, "card2");

        mainPnl.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(mainPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuBarHomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarHomeBtnActionPerformed
            newAppPnl.setVisible(false);
            SendAlternative.setVisible(false);
            porfilePnl.setVisible(false);
            p1.setVisible(true);

    }//GEN-LAST:event_menuBarHomeBtnActionPerformed

    private void menuBarEditprofileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarEditprofileBtnActionPerformed
       
            SendAlternative.setVisible(false); 
            newAppPnl.setVisible(false);
            p1.setVisible(false);
            porfilePnl.setVisible(true);
       
    }//GEN-LAST:event_menuBarEditprofileBtnActionPerformed

    private void menuBarExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarExitBtnActionPerformed
      
            dispose();

           
    }//GEN-LAST:event_menuBarExitBtnActionPerformed

    private void sendAlternativekButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendAlternativekButton6ActionPerformed
         p1.setVisible(false);
         newAppPnl.setVisible(false);
         porfilePnl.setVisible(false); 
        SendAlternative.setVisible(true); 

    }//GEN-LAST:event_sendAlternativekButton6ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked

    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel11mouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11mouseEntered
        if(evt.getSource()==jLabel11){
            jLabel11.setBackground(new Color(153,204,255));
        }
    }//GEN-LAST:event_jLabel11mouseEntered

    private void jLabel11mouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11mouseExited
        if(evt.getSource()==jLabel11){
            jLabel11.setBackground(new Color(0,0,255));
        }
    }//GEN-LAST:event_jLabel11mouseExited

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel19mouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19mouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19mouseEntered

    private void jLabel19mouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19mouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19mouseExited

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel21mouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21mouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21mouseEntered

    private void jLabel21mouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21mouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21mouseExited

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel22mouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22mouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22mouseEntered

    private void jLabel22mouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22mouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22mouseExited

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel23mouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23mouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel23mouseEntered

    private void jLabel23mouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23mouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel23mouseExited

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked

    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel24mouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24mouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel24mouseEntered

    private void jLabel24mouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24mouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel24mouseExited

    private void menuBarNewAppBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarNewAppBtnActionPerformed
            porfilePnl.setVisible(false);
            p1.setVisible(false);
            newAppPnl.setVisible(true);
      

            
           // TODO add your handling code here:
    }//GEN-LAST:event_menuBarNewAppBtnActionPerformed

    private void logoutBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutBtn1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressTxtfld;
    private javax.swing.JLabel ChooseSecondAterantivedateLbl;
    private javax.swing.JLabel NameTxtfld;
    private keeptoo.KGradientPanel SendAlternative;
    private javax.swing.JLabel addNotelbl;
    private javax.swing.JTextArea addnoteTexFld;
    private javax.swing.JLabel addressLbl;
    private javax.swing.JLabel appointmentDateLbl;
    private com.toedter.calendar.JDateChooser appointmentjDateChooserPatint;
    private javax.swing.JLabel chooseFirstAterantivedateLbl;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTxtfld;
    private javax.swing.JLabel familyNameLbl;
    private javax.swing.JLabel familynameTxtfld;
    private javax.swing.JLabel framePicLbl;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private keeptoo.KButton lmenuBarLogoutBtn;
    private keeptoo.KButton logoutBtn1;
    private keeptoo.KGradientPanel mainPnl;
    private keeptoo.KButton menuBarEditprofileBtn;
    private keeptoo.KButton menuBarExitBtn;
    private keeptoo.KButton menuBarHomeBtn;
    private keeptoo.KButton menuBarNewAppBtn;
    private javax.swing.JLabel nameLbl;
    private keeptoo.KGradientPanel newAppPnl;
    private keeptoo.KGradientPanel p1;
    private javax.swing.JScrollPane patientAppointmentTable;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JTextField phoneTxtfld;
    private keeptoo.KGradientPanel porfilePnl;
    private javax.swing.JLabel reminderLbl;
    private javax.swing.JTextField searchDistanceTexfld;
    private javax.swing.JLabel searchdistanceLbl;
    private keeptoo.KButton sendAlternativekButton6;
    private keeptoo.KButton sendAppointmntRequestBtn;
    private com.toedter.calendar.JDateChooser sendFirstAlternativejDateChooser;
    private keeptoo.KButton sendRequeskButton;
    private com.toedter.calendar.JDateChooser sendSecondAlternativejDateChooser;
    private javax.swing.JLabel specificationLbl;
    private javax.swing.JTextField specificationTxtfld;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JTextField titleTxtfld;
    private javax.swing.JLabel userNameLbl;
    private javax.swing.JTextField usernameTxtfld;
    private javax.swing.JLabel welcomNameLbl;
    private javax.swing.JLabel welcomeLbl;
    private javax.swing.JLabel yourAppointmenstLbl;
    // End of variables declaration//GEN-END:variables
}
