/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author Amar
 */
public class PhysicianGUI extends javax.swing.JFrame {
String id,email;
    /**
     * Creates new form tstkpoanels
     */
    public PhysicianGUI(Physician _physician) {
        nameTxtFld.setText(_physician.getFirstName());
        
        setUndecorated(true);
        getRootPane().setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, Color.BLACK));
      
        initComponents();
          userNameTexFld.setOpaque(false);
            userNameTexFld.setBorder(null);
             userNameTexFld.setEditable(false);
            
              
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPnl = new keeptoo.KGradientPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        homeBtn = new keeptoo.KButton();
        editprofileBtn = new keeptoo.KButton();
        logoutBtn = new keeptoo.KButton();
        exitBtn = new keeptoo.KButton();
        jLabel7 = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        homePanel = new keeptoo.KGradientPanel();
        sendAlternativekButton = new keeptoo.KButton();
        confirmkButton = new keeptoo.KButton();
        homeTable = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        porfilePnl = new keeptoo.KGradientPanel();
        nameLbl = new javax.swing.JLabel();
        nameTxtFld = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        FamilyNameTexfld = new javax.swing.JLabel();
        userNameLbl = new javax.swing.JLabel();
        TitleLbl = new javax.swing.JLabel();
        SpecificationLbl = new javax.swing.JLabel();
        addressLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        phoneLbl = new javax.swing.JLabel();
        familyNameTexFld = new javax.swing.JLabel();
        userNameTexFld = new javax.swing.JTextField();
        titleTxtFld = new javax.swing.JTextField();
        specificationTxtFld = new javax.swing.JTextField();
        addressTxtFld = new javax.swing.JTextField();
        emailTxtFld = new javax.swing.JTextField();
        phoneTxtFld = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        sendAtrernativePnl = new keeptoo.KGradientPanel();
        sendAternativejDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        sendBtn = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainPnl.setkEndColor(new java.awt.Color(255, 255, 255));
        mainPnl.setkStartColor(new java.awt.Color(153, 204, 255));
        mainPnl.setLayout(new java.awt.BorderLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/physicians-banner.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 743, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPnl.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        homeBtn.setBorder(null);
        homeBtn.setText("Home");
        homeBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        homeBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        homeBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        homeBtn.setkHoverStartColor(new java.awt.Color(102, 204, 255));
        homeBtn.setkPressedColor(new java.awt.Color(102, 204, 255));
        homeBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        homeBtn.setkStartColor(new java.awt.Color(153, 204, 255));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        editprofileBtn.setBorder(null);
        editprofileBtn.setText("Edit profile");
        editprofileBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        editprofileBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        editprofileBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        editprofileBtn.setkHoverStartColor(new java.awt.Color(102, 204, 255));
        editprofileBtn.setkPressedColor(new java.awt.Color(102, 204, 255));
        editprofileBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        editprofileBtn.setkStartColor(new java.awt.Color(153, 204, 255));
        editprofileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editprofileBtnActionPerformed(evt);
            }
        });

        logoutBtn.setBorder(null);
        logoutBtn.setText("Logout");
        logoutBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        logoutBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        logoutBtn.setkHoverStartColor(new java.awt.Color(102, 204, 255));
        logoutBtn.setkPressedColor(new java.awt.Color(102, 204, 255));
        logoutBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        logoutBtn.setkStartColor(new java.awt.Color(153, 204, 255));

        exitBtn.setBorder(null);
        exitBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        exitBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        exitBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        exitBtn.setkHoverStartColor(new java.awt.Color(102, 204, 255));
        exitBtn.setkPressedColor(new java.awt.Color(102, 204, 255));
        exitBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        exitBtn.setkStartColor(new java.awt.Color(153, 204, 255));
        exitBtn.setLabel("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", 2, 20)); // NOI18N
        jLabel7.setText("Welcome");

        welcomeLbl.setFont(new java.awt.Font("Baskerville Old Face", 2, 20)); // NOI18N
        welcomeLbl.setText("Name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
            .addComponent(editprofileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(welcomeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(logoutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(exitBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(welcomeLbl)
                .addGap(32, 32, 32)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editprofileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        mainPnl.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setLayout(new java.awt.CardLayout());

        homePanel.setkEndColor(new java.awt.Color(255, 255, 255));
        homePanel.setkStartColor(new java.awt.Color(153, 204, 255));

        sendAlternativekButton.setBorder(null);
        sendAlternativekButton.setText("Send alternative");
        sendAlternativekButton.setkEndColor(new java.awt.Color(102, 204, 255));
        sendAlternativekButton.setkForeGround(new java.awt.Color(102, 102, 102));
        sendAlternativekButton.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        sendAlternativekButton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        sendAlternativekButton.setkHoverStartColor(new java.awt.Color(102, 204, 255));
        sendAlternativekButton.setkPressedColor(new java.awt.Color(102, 204, 255));
        sendAlternativekButton.setkSelectedColor(new java.awt.Color(255, 255, 255));
        sendAlternativekButton.setkStartColor(new java.awt.Color(255, 255, 255));
        sendAlternativekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendAlternativekButtonActionPerformed(evt);
            }
        });

        confirmkButton.setBorder(null);
        confirmkButton.setText("Confirm");
        confirmkButton.setkEndColor(new java.awt.Color(102, 204, 255));
        confirmkButton.setkForeGround(new java.awt.Color(102, 102, 102));
        confirmkButton.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        confirmkButton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        confirmkButton.setkHoverStartColor(new java.awt.Color(102, 204, 255));
        confirmkButton.setkPressedColor(new java.awt.Color(102, 204, 255));
        confirmkButton.setkSelectedColor(new java.awt.Color(255, 255, 255));
        confirmkButton.setkStartColor(new java.awt.Color(255, 255, 255));
        confirmkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmkButtonActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(153, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "name 1", "last 1", "23", "xxx@...", null},
                {"2", "name 2", "last 2", "45", "xxx@...", null},
                {"3", "name 3", "last 3", "7", "xxx@...", null},
                {"4", "name 4", "last 4", "55", "xxx@...", null},
                {"5", "name 5", "last 5", "30", null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Date", "Age", "E-Mail", "Health problem"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        homeTable.setViewportView(jTable1);

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(homeTable, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmkButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendAlternativekButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(homeTable, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(sendAlternativekButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(confirmkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel3.add(homePanel, "card2");

        porfilePnl.setkEndColor(new java.awt.Color(255, 255, 255));
        porfilePnl.setkStartColor(new java.awt.Color(153, 204, 255));

        nameLbl.setText("Name");

        nameTxtFld.setText("jLabel10");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/edit.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PhysicianGUI.this.mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PhysicianGUI.this.mouseExited(evt);
            }
        });

        FamilyNameTexfld.setText("Family name");

        userNameLbl.setText("User name");

        TitleLbl.setText("Title");

        SpecificationLbl.setText("Specification");

        addressLbl.setText("Address");

        emailLbl.setText("E-Mail");

        phoneLbl.setText("Phone");

        familyNameTexFld.setText("jLabel18");

        userNameTexFld.setText("jTextField1");

        titleTxtFld.setText("jTextField2");

        specificationTxtFld.setText("jTextField3");

        addressTxtFld.setText("jTextField4");

        emailTxtFld.setText("jTextField5");

        phoneTxtFld.setText("jTextField6");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/edit.png"))); // NOI18N
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel19mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel19mouseExited(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/edit.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel21mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel21mouseExited(evt);
            }
        });

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/edit.png"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel22mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel22mouseExited(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/edit.png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel23mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel23mouseExited(evt);
            }
        });

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/edit.png"))); // NOI18N
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel24mouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel24mouseExited(evt);
            }
        });

        javax.swing.GroupLayout porfilePnlLayout = new javax.swing.GroupLayout(porfilePnl);
        porfilePnl.setLayout(porfilePnlLayout);
        porfilePnlLayout.setHorizontalGroup(
            porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(porfilePnlLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(porfilePnlLayout.createSequentialGroup()
                        .addComponent(addressLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21))
                    .addGroup(porfilePnlLayout.createSequentialGroup()
                        .addComponent(emailLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel23))
                    .addGroup(porfilePnlLayout.createSequentialGroup()
                        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, porfilePnlLayout.createSequentialGroup()
                                .addComponent(TitleLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(titleTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, porfilePnlLayout.createSequentialGroup()
                                .addComponent(phoneLbl)
                                .addGap(99, 99, 99)
                                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(specificationTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phoneTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addressTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(SpecificationLbl)
                            .addGroup(porfilePnlLayout.createSequentialGroup()
                                .addComponent(userNameLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(userNameTexFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(porfilePnlLayout.createSequentialGroup()
                        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FamilyNameTexfld)
                            .addComponent(nameLbl))
                        .addGap(70, 70, 70)
                        .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(familyNameTexFld, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 49, Short.MAX_VALUE)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        porfilePnlLayout.setVerticalGroup(
            porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(porfilePnlLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameLbl)
                    .addComponent(nameTxtFld))
                .addGap(18, 18, 18)
                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FamilyNameTexfld)
                    .addComponent(familyNameTexFld))
                .addGap(18, 18, 18)
                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(userNameLbl)
                        .addComponent(userNameTexFld, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TitleLbl)
                        .addComponent(titleTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SpecificationLbl)
                        .addComponent(specificationTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addressLbl)
                        .addComponent(addressTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailLbl)
                    .addComponent(emailTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(porfilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneLbl)
                    .addComponent(phoneTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jPanel3.add(porfilePnl, "card4");

        sendAtrernativePnl.setkEndColor(new java.awt.Color(255, 255, 255));
        sendAtrernativePnl.setkStartColor(new java.awt.Color(153, 204, 255));

        jLabel1.setText("Alternative date");

        jLabel2.setText("Add note");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        sendBtn.setBorder(null);
        sendBtn.setText("send");
        sendBtn.setkEndColor(new java.awt.Color(255, 255, 255));
        sendBtn.setkHoverEndColor(new java.awt.Color(255, 255, 255));
        sendBtn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        sendBtn.setkHoverStartColor(new java.awt.Color(102, 204, 255));
        sendBtn.setkPressedColor(new java.awt.Color(102, 204, 255));
        sendBtn.setkSelectedColor(new java.awt.Color(255, 255, 255));
        sendBtn.setkStartColor(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout sendAtrernativePnlLayout = new javax.swing.GroupLayout(sendAtrernativePnl);
        sendAtrernativePnl.setLayout(sendAtrernativePnlLayout);
        sendAtrernativePnlLayout.setHorizontalGroup(
            sendAtrernativePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sendAtrernativePnlLayout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addGroup(sendAtrernativePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sendAtrernativePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2)
                        .addGroup(sendAtrernativePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(sendAtrernativePnlLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(88, 88, 88)
                                .addComponent(sendAternativejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(100, 100, 100))
        );
        sendAtrernativePnlLayout.setVerticalGroup(
            sendAtrernativePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendAtrernativePnlLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(sendAtrernativePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sendAternativejDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(sendBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jPanel3.add(sendAtrernativePnl, "card2");

        mainPnl.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(mainPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPnl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
 
     
      porfilePnl.setVisible(false);
       homePanel.setVisible(true);
     

    }//GEN-LAST:event_homeBtnActionPerformed

    private void editprofileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editprofileBtnActionPerformed

     
      homePanel.setVisible(false);
      porfilePnl.setVisible(true);
     
       // TODO add your handling code here:
    }//GEN-LAST:event_editprofileBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
     
      dispose();
         
    }//GEN-LAST:event_exitBtnActionPerformed

    private void mouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseEntered
        if(evt.getSource()==jLabel11){
        jLabel11.setBackground(new Color(153,204,255));
        }
    }//GEN-LAST:event_mouseEntered

    private void mouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseExited
        if(evt.getSource()==jLabel11){
        jLabel11.setBackground(new Color(0,0,255));
        }
    }//GEN-LAST:event_mouseExited

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel19mouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19mouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19mouseEntered

    private void jLabel19mouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19mouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19mouseExited

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel21mouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21mouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21mouseEntered

    private void jLabel21mouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21mouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21mouseExited

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel22mouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22mouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22mouseEntered

    private void jLabel22mouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22mouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22mouseExited

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel23mouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23mouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel23mouseEntered

    private void jLabel23mouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23mouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel23mouseExited

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
      }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel24mouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24mouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel24mouseEntered

    private void jLabel24mouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24mouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel24mouseExited

    private void sendAlternativekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendAlternativekButtonActionPerformed
    
       porfilePnl.setVisible(false);
       homePanel.setVisible(false);
       sendAtrernativePnl.setVisible(true);
       
                                      
    }//GEN-LAST:event_sendAlternativekButtonActionPerformed

    private void confirmkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmkButtonActionPerformed
String username = "amaramkooooo@gmail.com";
		String password = "Mnb12345!";

		MailSender sender = new MailSender();
		sender.login("smtp.gmail.com", "587", username, password);

		try {

			sender.send("amaramkooooo@gmail.com", " Amar Planincic","amaramko@live.com", "Test Test Test Betreff",
					"Your appointment is confirmed and we are looking forward to see you on :"+new testDatabase().getsuggestedappointmentdate(1));

		} catch (Exception e) {
			e.printStackTrace();
		}
                JOptionPane.showMessageDialog(new sendEmailfrm(),"Your E-Mail has been sent successfully !");  
    }//GEN-LAST:event_confirmkButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    int index=jTable1.getSelectedRow();
    TableModel model=jTable1.getModel();
    
    id=model.getValueAt(index,0).toString();
    email=model.getValueAt(index,4).toString();
        System.out.println(id);
        System.out.println(email);
          
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhysicianGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhysicianGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhysicianGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhysicianGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
      /*  java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhysicianGUI().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FamilyNameTexfld;
    private javax.swing.JLabel SpecificationLbl;
    private javax.swing.JLabel TitleLbl;
    private javax.swing.JLabel addressLbl;
    private javax.swing.JTextField addressTxtFld;
    private keeptoo.KButton confirmkButton;
    private keeptoo.KButton editprofileBtn;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTxtFld;
    private keeptoo.KButton exitBtn;
    private javax.swing.JLabel familyNameTexFld;
    private keeptoo.KButton homeBtn;
    private keeptoo.KGradientPanel homePanel;
    private javax.swing.JScrollPane homeTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private keeptoo.KButton logoutBtn;
    private keeptoo.KGradientPanel mainPnl;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel nameTxtFld;
    private javax.swing.JLabel phoneLbl;
    private javax.swing.JTextField phoneTxtFld;
    private keeptoo.KGradientPanel porfilePnl;
    private keeptoo.KButton sendAlternativekButton;
    private com.toedter.calendar.JDateChooser sendAternativejDateChooser;
    private keeptoo.KGradientPanel sendAtrernativePnl;
    private keeptoo.KButton sendBtn;
    private javax.swing.JTextField specificationTxtFld;
    private javax.swing.JTextField titleTxtFld;
    private javax.swing.JLabel userNameLbl;
    private javax.swing.JTextField userNameTexFld;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
