/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

/**
 *
 * @author Amar
 */
public class siglePanel extends javax.swing.JFrame {
    
     private javax.swing.JButton Nextbtnp2;
    private javax.swing.JLabel agelbl1;
    private javax.swing.JButton backBtnp2;
    private javax.swing.JLabel dbHealthprblemLbl1;
    private javax.swing.JLabel dbNamelbl1;
    private javax.swing.JLabel dbagelbl1;
    private javax.swing.JLabel dbsuggestedappointmentdateLbl1;
    private javax.swing.JLabel healthproblemlbl1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel namelbl2;
    private javax.swing.JPanel p2;
    private javax.swing.JLabel suggestedappointmentdate1;
    int i=1;
    int j=0;

    public siglePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        p2 = new javax.swing.JPanel();
        namelbl2 = new javax.swing.JLabel();
        agelbl1 = new javax.swing.JLabel();
        healthproblemlbl1 = new javax.swing.JLabel();
        suggestedappointmentdate1 = new javax.swing.JLabel();
        dbNamelbl1 = new javax.swing.JLabel();
        dbagelbl1 = new javax.swing.JLabel();
        dbHealthprblemLbl1 = new javax.swing.JLabel();
        dbsuggestedappointmentdateLbl1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Nextbtnp2 = new javax.swing.JButton();
        backBtnp2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        p2.setBackground(new java.awt.Color(153, 255, 153));
        p2.setForeground(new java.awt.Color(153, 255, 255));

        namelbl2.setText("Patiient Name :");

        agelbl1.setText("Age :");

        healthproblemlbl1.setText("Health problem :");

        suggestedappointmentdate1.setText("Appointment date :");

        dbNamelbl1.setText(new testDatabase().getUsername(i));


        dbagelbl1.setText(new testDatabase().getAge(i));

        dbHealthprblemLbl1.setText(new testDatabase().gethealthproblem(i));

        dbsuggestedappointmentdateLbl1.setText(new testDatabase().getsuggestedappointmentdate(i));

        jButton1.setText("send alternative");

        Nextbtnp2.setBackground(new java.awt.Color(153, 153, 153));
        Nextbtnp2.setText("next");
        Nextbtnp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nextbtnp2ActionPerformed(evt);
            }
        });

        backBtnp2.setText("back");
        backBtnp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnp2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p2Layout.createSequentialGroup()
                        .addContainerGap(75, Short.MAX_VALUE)
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(agelbl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namelbl2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(healthproblemlbl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(suggestedappointmentdate1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(dbagelbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dbHealthprblemLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dbNamelbl1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p2Layout.createSequentialGroup()
                                .addComponent(dbsuggestedappointmentdateLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(p2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backBtnp2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nextbtnp2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namelbl2)
                    .addComponent(dbNamelbl1))
                .addGap(28, 28, 28)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agelbl1)
                    .addComponent(dbagelbl1))
                .addGap(33, 33, 33)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(healthproblemlbl1)
                    .addComponent(dbHealthprblemLbl1))
                .addGap(23, 23, 23)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suggestedappointmentdate1)
                    .addComponent(dbsuggestedappointmentdateLbl1)
                    .addComponent(jButton1))
                .addGap(51, 51, 51)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nextbtnp2)
                    .addComponent(backBtnp2))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>                        

    private void Nextbtnp2ActionPerformed(java.awt.event.ActionEvent evt) {                                          
     
     i++;
      dbNamelbl1.setText(new testDatabase().getUsername(i));


        dbagelbl1.setText(new testDatabase().getAge(i));

        dbHealthprblemLbl1.setText(new testDatabase().gethealthproblem(i));

        dbsuggestedappointmentdateLbl1.setText(new testDatabase().getsuggestedappointmentdate(i));
      

    }                                         

    private void backBtnp2ActionPerformed(java.awt.event.ActionEvent evt) {      
    
        j=i-1;
        dbNamelbl1.setText(new testDatabase().getUsername(j));


        dbagelbl1.setText(new testDatabase().getAge(j));

        dbHealthprblemLbl1.setText(new testDatabase().gethealthproblem(j));

        dbsuggestedappointmentdateLbl1.setText(new testDatabase().getsuggestedappointmentdate(j));
        
        i--;
    }                                         


                   
}
